[I] Loading dataset ZINC, fold 1...
train, test, val sizes : 10000 1000 1000
[I] Finished loading.
[I] Data load time: 10.7097s
0it [00:00, ?it/s]0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/p/psoga/benchmarking-gnns/main_molecules_graph_regression.py", line 359, in <module>
    main()    
  File "/afs/crc.nd.edu/user/p/psoga/benchmarking-gnns/main_molecules_graph_regression.py", line 357, in main
    train_val_pipeline(MODEL_NAME, dataset, params, net_params, dirs, params['save_name'])
  File "/afs/crc.nd.edu/user/p/psoga/benchmarking-gnns/main_molecules_graph_regression.py", line 158, in train_val_pipeline
    epoch_train_loss, epoch_train_mae, optimizer = train_epoch(model, optimizer, device, train_loader, epoch, MODEL_NAME)
  File "/afs/crc.nd.edu/user/p/psoga/benchmarking-gnns/train/train_molecules_graph_regression.py", line 20, in train_epoch_sparse
    for iter, data in tqdm(enumerate(data_loader)):
  File "/afs/crc.nd.edu/user/p/psoga/.conda/envs/gnn/lib/python3.10/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/afs/crc.nd.edu/user/p/psoga/.conda/envs/gnn/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/afs/crc.nd.edu/user/p/psoga/.conda/envs/gnn/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 692, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/afs/crc.nd.edu/user/p/psoga/.conda/envs/gnn/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/afs/crc.nd.edu/user/p/psoga/benchmarking-gnns/data/molecules.py", line 370, in collate
    spatial_pos_bias[idx >= 20] = float("-inf")
RuntimeError: value cannot be converted to type int64_t without overflow
